# tasks file for swarm_cluster
---
- name: Get OS Family
  ansible.builtin.setup:
    gather_subset:
      - distribution

- name: Install Docker on RHEL-based Systems
  import_tasks: install_rhel.yml
  when: ansible_os_family == "RedHat"

- name: Install Docker on Debian-based Systems
  import_tasks: install_debian.yml
  when: ansible_os_family == "Debian"

- name: Ensure Docker service is started
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Initialize Swarm Master Node (if applicable)
  import_tasks: init_master.yml
  when: master_node is defined

- name: Join Worker Nodes to Swarm Cluster
  import_tasks: worker_join.yml
  when: master_node is defined and master_node not in ansible_all_ipv4_addresses