---
galaxy_info:
  author: Michael Winchester
  description: Deploy Opensips using Docker compose 
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Debian
      versions:
        - "10"
        - "11"
  categories:
    - cloud
    - system
dependencies: []